dbt_demo_POMProductView:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: sandbox-07454903# Replace this with your project id
      dataset: dbt_demo_AR  # Replace this with dbt_your_name, e.g. dbt_bob
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      keyfile: "{{ env_var('BIGQUERY_KEYFILE') }}"